# Credits

This is heavily based on https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used. If you have a cuda enabled machine, read the README.md in the root of this repo on how to use nvidia-docker.


It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [1]:
import torch

Construct a 5x3 matrix, uninitialized

In [2]:
x = torch.Tensor(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


Construct a randomly initialized matrix

In [13]:
x = torch.rand(5, 3)
print(x)

tensor([[0.1519, 0.3418, 0.1698],
        [0.4159, 0.4048, 0.3079],
        [0.4604, 0.2354, 0.7002],
        [0.8142, 0.0366, 0.9000],
        [0.5943, 0.1187, 0.6620]])


Get its size

In [14]:
print(x.size())

torch.Size([5, 3])


**NOTE**: `torch.Size` is in fact a tuple, so it supports the same operations that a tuple supports.

In [15]:
x[:1,:1] = 2
print(x)

tensor([[2.0000, 0.3418, 0.1698],
        [0.4159, 0.4048, 0.3079],
        [0.4604, 0.2354, 0.7002],
        [0.8142, 0.0366, 0.9000],
        [0.5943, 0.1187, 0.6620]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [19]:
# a tensor size of 2x17
x = torch.Tensor(2,17)
print(x)
print(x.size())

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])
torch.Size([2, 17])


In [20]:
# a torch.FlaotTensor of size 3x1
x = torch.FloatTensor(3,1)
print(x)
print(x.size())

tensor([[0.],
        [0.],
        [0.]])
torch.Size([3, 1])


In [22]:
# a torch.LongTensor of size (5,2,1)
x = torch.LongTensor(5,2,1)
print(x)
print(x.size())

x[:,:] = 7
print(x)

tensor([[[0],
         [0]],

        [[0],
         [0]],

        [[0],
         [0]],

        [[0],
         [0]],

        [[0],
         [0]]])
torch.Size([5, 2, 1])
tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]]])


In [25]:
# a torch.ByteTensor of size (5,)
x = torch.ByteTensor(5)
print(x)
print(x.size())

x[1:4] = 1
print(x)

tensor([0, 0, 0, 0, 0], dtype=torch.uint8)
torch.Size([5])
tensor([0, 1, 1, 1, 0], dtype=torch.uint8)


## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [26]:
x = torch.rand(5,3)
y = torch.rand(5, 3)
print(x + y)

tensor([[0.3385, 1.7905, 1.1983],
        [0.9791, 0.9976, 0.2545],
        [1.4235, 0.5550, 0.7831],
        [0.4093, 0.9097, 1.3083],
        [0.7246, 1.0622, 0.7223]])


### 2.2 Addition: syntax 2

In [27]:
print(torch.add(x, y))

tensor([[0.3385, 1.7905, 1.1983],
        [0.9791, 0.9976, 0.2545],
        [1.4235, 0.5550, 0.7831],
        [0.4093, 0.9097, 1.3083],
        [0.7246, 1.0622, 0.7223]])


### 2.3 Addition: giving an output tensor

In [28]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.3385, 1.7905, 1.1983],
        [0.9791, 0.9976, 0.2545],
        [1.4235, 0.5550, 0.7831],
        [0.4093, 0.9097, 1.3083],
        [0.7246, 1.0622, 0.7223]])


### 2.4 Addition: in-place

adds `x`to `y`

In [29]:
y.add_(x)
print(y)

tensor([[0.3385, 1.7905, 1.1983],
        [0.9791, 0.9976, 0.2545],
        [1.4235, 0.5550, 0.7831],
        [0.4093, 0.9097, 1.3083],
        [0.7246, 1.0622, 0.7223]])


**NOTE**: Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [30]:
print(x[:, 1])

tensor([0.9093, 0.9325, 0.4639, 0.7446, 0.5302])


**Read later** 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [41]:
# multiplication of two tensors
x = torch.ones(5, 3)
y = torch.rand(5, 3)
print(x)
print(y)
print(x.mul(y))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.9008, 0.6657, 0.8758],
        [0.9978, 0.8157, 0.5898],
        [0.3967, 0.4197, 0.0529],
        [0.2777, 0.0317, 0.3334],
        [0.9987, 0.4718, 0.0855]])
tensor([[0.9008, 0.6657, 0.8758],
        [0.9978, 0.8157, 0.5898],
        [0.3967, 0.4197, 0.0529],
        [0.2777, 0.0317, 0.3334],
        [0.9987, 0.4718, 0.0855]])


In [37]:
# in-place multiplication
y.mul_(x)
print(y)

tensor([[0.9565, 0.2590, 0.1166],
        [0.4647, 0.6698, 0.3572],
        [0.7999, 0.7893, 0.4947],
        [0.6144, 1.0000, 0.5506],
        [0.6914, 0.6213, 0.8705]])


In [38]:
# torch division
x.div(y)

tensor([[1.0454, 3.8607, 8.5790],
        [2.1521, 1.4930, 2.7996],
        [1.2501, 1.2670, 2.0216],
        [1.6275, 1.0000, 1.8161],
        [1.4463, 1.6094, 1.1487]])

In [42]:
# matrix multiplication
x = torch.rand(2,4)
y = torch.rand(4,2)
print(x.mm(y))

tensor([[0.3868, 1.0542],
        [0.6799, 2.2479]])


## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [43]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [44]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value: the `numpy()` method provides a *view* of the original tensor, not a copy.

In [45]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [46]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a numpy array
3. now convert it back to a torch tensor

In [47]:
x = torch.ones(5,2)
y = x.numpy()
z = torch.from_numpy(y)

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [48]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # Notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # This is meant as a tensor to be run on the GPU.
    # The .cuda() does this to any parameter it is applied to.
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")

CUDA not available on your machine.


In [49]:
torch.cuda.is_available()

False